global:
  scrape_interval: 30s  # scrape every 5 seconds
  evaluation_interval: 59s  # evaluate rules every 5 secs

rule_files:
  - "one_rule.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']
  - job_name: 'users-backend-service'
    metrics_path: /actuator/prometheus
    scrape_interval: 30s
    static_configs:
      - targets: ['host.docker.internal:8080']  # host and port
    bearer_token: "eyJhbGciOiJSUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI2Z1dON0JaRkJ6cHp2cnpkdnhJaGRrMkRXZGI2MHFmU0NwYWNVNWI2Mno4In0.eyJleHAiOjE3MjMxNjQyNjksImlhdCI6MTcyMzEyODI2OSwianRpIjoiZGVmY2MzZGItZTAwMi00OWVhLTk1NGQtMGZlNDVhNTQ2ZTRhIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDoxODA4MC9yZWFsbXMvY2VsZXN0aWFsLWZvcmdlIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6IjQ0MDcwOWJiLWNlZmEtNDc2Yy04ZTg3LWNkZGZjOGYyY2QzMSIsInR5cCI6IkJlYXJlciIsImF6cCI6ImtleWNsb2FrLWlhbS1zcHJpbmctc2VjdXJpdHkiLCJzZXNzaW9uX3N0YXRlIjoiYWRlNjVmMzQtZmRlZi00ZDA0LTgzNjUtYjAwNTg3NDM1ZDY2IiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJFTVBMT1lFRSIsIm9mZmxpbmVfYWNjZXNzIiwiTUFOQUdFUiIsIkhSIiwidW1hX2F1dGhvcml6YXRpb24iLCJBRE1JTiIsIlVTRVIiLCJkZWZhdWx0LXJvbGVzLWNlbGVzdGlhbGZvcmdlIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsia2V5Y2xvYWstaWFtLXNwcmluZy1zZWN1cml0eSI6eyJyb2xlcyI6WyJjbGllbnRfZW1wbG95ZWUiLCJjbGllbnRfbWFuYWdlciIsImNsaWVudF91c2VyIiwiY2xpZW50X2FkbWluIiwiY2xpZW50X2hyIl19LCJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJzaWQiOiJhZGU2NWYzNC1mZGVmLTRkMDQtODM2NS1iMDA1ODc0MzVkNjYiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6IkNlbGVzdGlhbCBGb3JnZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImNlbGVzdGlhbCIsImdpdmVuX25hbWUiOiJDZWxlc3RpYWwiLCJsb2NhbGUiOiJlbiIsImZhbWlseV9uYW1lIjoiRm9yZ2UiLCJlbWFpbCI6ImNlbGVzdGlhbEBlbWFpbC5jb20ifQ.g6s_T6GX7HDbbOaY3bjjTu4tyZ_njTjZM1YWAPS6CXV_cKHcEPm8b9PGQUTuMylXFkHGBerjUu7UyT2oWYRkURLHV9Z8CR7EQL_iq9Ih3N1JontDlbki0_sDL0Bc_EeczVJGNDzoZqGE98Hz_vrIbgHgXb76GPIWg9dVNHG82qEVwgWWWbQV1KyvV8zOdC0nyESNv7RKateZhtJKYFQr0PYYupWpbSt6kOBMn9QgOB_ha2jpjz-ATMKEDx-ldd4hKiZ1YfnZXCqRgjc8rFziz0-v0hjHn0juIzWTL3FEk5p6xxYLznbofLeUuvTxOIkJfIf8l5B62A5yIE-1bqiZmw"

#    basic_auth:
#      username: "admin"
#      password: "pass"
