global:
  scrape_interval: 30s  # scrape every 5 seconds
  evaluation_interval: 59s  # evaluate rules every 5 secs

rule_files:
  - "one_rule.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']
  - job_name: 'users-backend-service'
    metrics_path: /actuator/prometheus
    scrape_interval: 30s
    static_configs:
      - targets: ['host.docker.internal:8080']  # host and port
    bearer_token: "eyJhbGciOiJSUzUxMiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICI2Z1dON0JaRkJ6cHp2cnpkdnhJaGRrMkRXZGI2MHFmU0NwYWNVNWI2Mno4In0.eyJleHAiOjE3MjQ0ODA0MDcsImlhdCI6MTcyNDQ0NDQwNywianRpIjoiN2NmNjBlNzQtNGE2Yy00ZjdkLWJiNDEtMzk2YjgwNDg3NWM3IiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDoxODA4MC9yZWFsbXMvY2VsZXN0aWFsLWZvcmdlIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6IjQ0MDcwOWJiLWNlZmEtNDc2Yy04ZTg3LWNkZGZjOGYyY2QzMSIsInR5cCI6IkJlYXJlciIsImF6cCI6ImtleWNsb2FrLWlhbS1zcHJpbmctc2VjdXJpdHkiLCJzZXNzaW9uX3N0YXRlIjoiYzRiYmY0NWMtMTIxNS00ZDg2LTk3ZmQtMTkwMTgwY2M5NDk5IiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyIqIl0sInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJFTVBMT1lFRSIsIm9mZmxpbmVfYWNjZXNzIiwiTUFOQUdFUiIsIkhSIiwidW1hX2F1dGhvcml6YXRpb24iLCJBRE1JTiIsIlVTRVIiLCJkZWZhdWx0LXJvbGVzLWNlbGVzdGlhbGZvcmdlIl19LCJyZXNvdXJjZV9hY2Nlc3MiOnsia2V5Y2xvYWstaWFtLXNwcmluZy1zZWN1cml0eSI6eyJyb2xlcyI6WyJjbGllbnRfZW1wbG95ZWUiLCJjbGllbnRfbWFuYWdlciIsImNsaWVudF91c2VyIiwiY2xpZW50X2FkbWluIiwiY2xpZW50X2hyIl19LCJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJzaWQiOiJjNGJiZjQ1Yy0xMjE1LTRkODYtOTdmZC0xOTAxODBjYzk0OTkiLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwibmFtZSI6IkNlbGVzdGlhbCBGb3JnZSIsInByZWZlcnJlZF91c2VybmFtZSI6ImNlbGVzdGlhbCIsImdpdmVuX25hbWUiOiJDZWxlc3RpYWwiLCJsb2NhbGUiOiJlbiIsImZhbWlseV9uYW1lIjoiRm9yZ2UiLCJlbWFpbCI6ImNlbGVzdGlhbEBlbWFpbC5jb20ifQ.QbFMp166VqiCRucoBW24mteFADTv1VieTiQYJnurJ1kNxcHWesZAxOMuGi-wFVpb_Dwe-1k7agRLUclhQriiqbtp8XoPsYfYFvTJ7D9bp-W_6hsV40zeF-6hmVt-f5rBHgCCSY2Rp0uY9kq5Uf6q2OCd_fEdkcdxguPQqcmcn5ASqsXhTRYzHU_Naevs3Fq0XgRgbrz40tPEKEcKSXnCD3lHbMc-5bT88d6xkJNzjFhDuY8VJY3PK-Gtg5CEUSZ-jeA8n7H7vFTB7PqkhScCyhlobLe0kVcw8lMCVBkNHLAmmiB0vlUB-OxJoub6Zz_vmTyeoBMMh1Gjgo6jNJPg2g"

#    basic_auth:
#      username: "admin"
#      password: "pass"
